/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.sena.vista.conductor;

import co.edu.sena.control.conductor.controlConductor;
import co.edu.sena.dto.conductor.DTOConductor;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author sena
 */
public class viewConductor extends javax.swing.JFrame {
        String cedula="";
        String nombre="";
        String apellido="";
        String direccion="";
        String tel="";
        String movil="";
        String fecha_n="";
        int codConductor=100;
        int contador=0;
 
        String [][] datos= new String [20][20];
        controlConductor ctrlConductor1=new controlConductor();
        DTOConductor[] dtoConductor=new DTOConductor[10];
    /**
     * Creates new form viewConductor
     */
    public viewConductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registro = new javax.swing.JButton();
        cedula1 = new javax.swing.JTextField();
        nombre1 = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        tel1 = new javax.swing.JTextField();
        movil1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        direccion1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fechan1 = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CONDUCTOR");

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Telefono");

        registro.setText("REGISTRAR");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Foto");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/vista/conductor/LOGO.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Cedula", "Nombres", "Apellidos", "Fecha de nacimiento", "Direccion", "Telefono", "Movil"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jLabel9.setText("Movil");

        borrar.setText("BORRAR");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel6.setText("              foto");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Direccion");

        jLabel11.setText("Fecha de nacimiento");

        actualizar.setText("MODIFICAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registro)
                .addGap(18, 18, 18)
                .addComponent(borrar)
                .addGap(18, 18, 18)
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(actualizar)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(202, 202, 202))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(movil1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(apellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(tel1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(direccion1)
                                    .addComponent(fechan1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(movil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscar)
                        .addComponent(borrar)
                        .addComponent(actualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1ActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        
        cedula=cedula1.getText();
        nombre=nombre1.getText();
        apellido=apellido1.getText();
        fecha_n=fechan1.getText();
        direccion=direccion1.getText();
        tel=tel1.getText();
        movil=movil1.getText();
        
        
        dtoConductor[contador]=new DTOConductor();
        dtoConductor[contador].setCedula(cedula);
        dtoConductor[contador].setNombre(nombre);
        dtoConductor[contador].setApellido(apellido);
        dtoConductor[contador].setDireccion(fecha_n);
        dtoConductor[contador].setDireccion(direccion);
        dtoConductor[contador].setTelefono(tel);
        dtoConductor[contador].setMovil(movil);
        
        if(ctrlConductor1.ingresarConductor(dtoConductor[contador]))
        { 
          datos[contador][0]=String.valueOf(codConductor);
          datos[contador][1]=cedula;
          datos[contador][2]=nombre;
          datos[contador][3]=apellido;
          datos[contador][4]=fecha_n;
          datos[contador][5]=direccion;
          datos[contador][6]=tel;
          datos[contador][7]=movil;
        
         tabla.setModel(new javax.swing.table.DefaultTableModel(
           datos,
            new String [] {
                "DNI","Cedula", "Nombres", "Apellidos", "Fecha de nacimiento", "Direccin", "Telefono", "Movil"
            }
        ));
          contador=contador+1;
          cedula1.setText("");
          nombre1.setText("");
          apellido1.setText("");
          fechan1.setText("");
          direccion1.setText("");
          tel1.setText("");
          movil1.setText("");
          codConductor=codConductor+2;
        }
        for(int i=0 ;i<contador;i++){ 
        try{
            String foto = datos[i][1] + ".jpg";
            ImageIcon icono = new ImageIcon(getClass().getResource(foto));
            Image image = icono.getImage();
            Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
            icono = new ImageIcon(newimg);
            jLabel6.setIcon(icono);}
         
         
            catch(Exception e){
                    
            String foto =  "not.png";
            ImageIcon icono = new ImageIcon(getClass().getResource(foto));
            Image image = icono.getImage();
            Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
            icono = new ImageIcon(newimg);
            jLabel6.setIcon(icono);
            }
       }
        
    }//GEN-LAST:event_registroActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
     if(ctrlConductor1.eliminarConductor(dtoConductor[contador])){
            if(contador<=0){
            contador=0;}
        else{
        contador--;
        }
          datos[contador][0]= ""; 
          datos[contador][1]= "";
          datos[contador][2]= "";
          datos[contador][3]= "";
          datos[contador][4]= "";
          datos[contador][5]= "";
          datos[contador][6]= "";
          datos[contador][7]= "";
         tabla.setModel(new javax.swing.table.DefaultTableModel(
           datos,
            new String [] {
                "DNI", "Cedula", "Nombres", "Apellidos","Fecha de nacimiento", "Telefono", "Movil"
            }
        )); 
       
       }
        
    }//GEN-LAST:event_borrarActionPerformed
  
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
         for(int i=0 ;i<contador;i++){
             
        if(datos[i][1].equals(cedula1.getText())){
        
            nombre1.setText(datos[i][2]);
            apellido1.setText(datos[i][3]);
            fechan1.setText(datos[i][4]);
            direccion1.setText(datos[i][5]);
            tel1.setText(datos[i][6]);
            movil1.setText(datos[i][7]);
    
         try{  
            String foto = datos[i][1] + ".jpg";
            ImageIcon icono = new ImageIcon(getClass().getResource(foto));
            Image image = icono.getImage();
            Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
            icono = new ImageIcon(newimg);
            jLabel6.setIcon(icono);}
         
         
            catch(Exception e){
                    
            String foto =  "not.png";
            ImageIcon icono = new ImageIcon(getClass().getResource(foto));
            Image image = icono.getImage();
            Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
            icono = new ImageIcon(newimg);
            jLabel6.setIcon(icono);
            }
         }}
    }//GEN-LAST:event_buscarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        for(int i=0 ;i<contador;i++){
             
        if(datos[i][1].equals(cedula1.getText())){
        
        cedula=cedula1.getText();
        nombre=nombre1.getText();
        apellido=apellido1.getText();
        fecha_n=fechan1.getText();
        direccion=direccion1.getText();
        tel=tel1.getText();
        movil=movil1.getText();
        
        
          datos[i][1]=cedula;
          datos[i][2]=nombre;
          datos[i][3]=apellido;
          datos[i][4]=fecha_n;
          datos[i][5]=direccion;
          datos[i][6]=tel;
          datos[i][7]=movil;
          
          tabla.setModel(new javax.swing.table.DefaultTableModel(
           datos,
            new String [] {
                "DNI", "Cedula", "Nombres", "Apellidos","Fecha de nacimiento", "Telefono", "Movil"
            }
        )); 
         }  
        }
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField apellido1;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cedula1;
    private javax.swing.JTextField direccion1;
    private javax.swing.JTextField fechan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField movil1;
    private javax.swing.JTextField nombre1;
    private javax.swing.JButton registro;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tel1;
    // End of variables declaration//GEN-END:variables
}
